In [122]:
import numpy as np
import pandas as pd 
from numpy import array
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [123]:
data = pd.read_csv('/Users/Fox/Desktop/Data Science/Capstone/Codes/EDA-Siqi/EDA.csv', index_col=0)
data

Type  Breed1  Breed2  Gender  Color1  Color2  Color3  MaturitySize  \
0         0     167       0       1       0       6       0             3   
1         0     136       0       1       0       1       0             2   
2         1     175       0       1       1       6       0             2   
3         1     175       0       0       0       1       0             2   
4         1     175       0       1       0       0       0             2   
...     ...     ...     ...     ...     ...     ...     ...           ...   
14987     1      89       0       0       0       6       0             3   
14988     0     137       0       2       0       0       0             2   
14989     0     136     100       2       0       3       5             2   
14990     0     136     102       2       4       5       5             1   
14991     0     137       0       0       3       6       0             3   

       FurLength  Vaccinated  Dewormed  Sterilized  Health  Quantity  \
0              2           0         0           0       0         0   
1              1           1         1           1       0         0   
2              1           2         2           0       0         0   
3              2           2         2           0       0         0   
4              2           0         0           0       0         0   
...          ...         ...       ...         ...     ...       ...   
14987          0           2         2           0       0         0   
14988          1           0         0           0       0         3   
14989          1           2         2           2       0         1   
14990          1           0         2           1       0         4   
14991          2           2         2           2       0         0   

       VideoAmt  PhotoAmt  AdoptionSpeed  AgeBins  Pure_breed  Free_or_NeedFee  
0             0         1              2        0           1                1  
1             0         2              4        0           1                0  
2             0         7              1        0           1                0  
3             0         8              2        0           1                1  
4             0         3              2        0           1                0  
...         ...       ...            ...      ...         ...              ...  
14987         0         1              4        1           1                0  
14988         0         3              2        0           1                0  
14989         0         3              3        4           0                0  
14990         0         5              1        0           0                1  
14991         0         3              3        1           1                0  

[14617 rows x 20 columns]

In [124]:
df = pd.DataFrame(data) 

In [125]:
# Drop Breed1 Breed2
#X = df[['Type', 'Gender', 'Color1', 'Color2', 'Color3', 'MaturitySize',
#       'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health',
#       'Quantity', 'VideoAmt', 'PhotoAmt',  'AgeBins',
#       'Pure_breed', 'Free_or_NeedFee']].values

# Selected Feature
X = df[['PhotoAmt','MaturitySize','FurLength','Color1','VideoAmt','Quantity','Dewormed','Sterilized','AgeBins','Vaccinated', 'Gender']].values

In [126]:
X

array([[1, 3, 2, ..., 0, 0, 1],
       [2, 2, 1, ..., 0, 1, 1],
       [7, 2, 1, ..., 0, 2, 1],
       ...,
       [3, 2, 1, ..., 4, 2, 2],
       [5, 1, 1, ..., 0, 0, 2],
       [3, 3, 2, ..., 1, 2, 0]])

In [127]:
y = np.array(df['AdoptionSpeed'].tolist())

## SMOTE

In [128]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE
print('Original dataset shape %s' % Counter(y))

Original dataset shape Counter({3: 4115, 2: 3923, 1: 3156, 0: 3020, 4: 403})


In [129]:
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X, y)
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({2: 4115, 4: 4115, 1: 4115, 0: 4115, 3: 4115})


## Data Spliting

In [130]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size = 0.30)

In [131]:
X

array([[1, 3, 2, ..., 0, 0, 1],
       [2, 2, 1, ..., 0, 1, 1],
       [7, 2, 1, ..., 0, 2, 1],
       ...,
       [3, 2, 1, ..., 4, 2, 2],
       [5, 1, 1, ..., 0, 0, 2],
       [3, 3, 2, ..., 1, 2, 0]])

In [132]:
y_train

array([4, 2, 3, ..., 2, 2, 4])

## SVM

In [133]:
#svclassifier = SVC(kernel='linear')
svclassifier = SVC(kernel='rbf') #Gaussian Kernel
#svclassifier = SVC(kernel='poly', degree=9) #Polynomial kernel
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [134]:
y_pred = svclassifier.predict(X_test)

In [135]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[369 155  56 227 470]
 [236 255  71 327 310]
 [283 243  77 296 357]
 [175 135  49 565 277]
 [166  61  11 199 803]]
              precision    recall  f1-score   support

           0       0.30      0.29      0.29      1277
           1       0.30      0.21      0.25      1199
           2       0.29      0.06      0.10      1256
           3       0.35      0.47      0.40      1201
           4       0.36      0.65      0.46      1240

    accuracy                           0.34      6173
   macro avg       0.32      0.34      0.30      6173
weighted avg       0.32      0.34      0.30      6173



In [136]:
def Manually_check(X,y):
    PRED = svclassifier.predict(X)
    LABEL = y
    return PRED,y

In [137]:
Manually_check(X[0:5],y[0:5])

(array([4, 4, 1, 1, 0]), array([2, 4, 1, 2, 2]))

In [138]:
X[9]

array([2, 2, 1, 0, 0, 0, 1, 1, 2, 1, 0])

## MLP

In [139]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='sgd', alpha=1e-5,
                    hidden_layer_sizes=(500, 200), random_state=1)
clf.fit(X_res, y_res)
print("Training set score: %f" % clf.score(X_train, y_train))
print("Test set score: %f" % clf.score(X_test, y_test))

Training set score: 0.403833
Test set score: 0.387818


/Users/Fox/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [140]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.34      0.36      0.35      1277
           1       0.35      0.26      0.30      1199
           2       0.32      0.14      0.19      1256
           3       0.41      0.44      0.42      1201
           4       0.44      0.74      0.55      1240

    accuracy                           0.39      6173
   macro avg       0.37      0.39      0.36      6173
weighted avg       0.37      0.39      0.36      6173



In [141]:
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])

weights between input and first hidden layer:
[[ 0.00891631  0.06626618 -0.09353723 ...  0.05032894  0.11037466
  -0.08172269]
 [-0.10483848 -0.05289907 -0.07276033 ...  0.0417558  -0.06016979
   0.0875722 ]
 [-0.04970676  0.09224272  0.04594831 ...  0.08540063 -0.016392
   0.08725682]
 ...
 [-0.02039694  0.05276588 -0.02695865 ... -0.04601996 -0.02733221
  -0.13229463]
 [ 0.03273108  0.09943298 -0.04363987 ... -0.03317946  0.16667586
  -0.1468383 ]
 [ 0.02512696  0.04256352 -0.0881324  ...  0.0193815  -0.00487955
  -0.09076789]]

weights between first hidden and second hidden layer:
[[ 0.02913121  0.07984715  0.08335089 ... -0.07245357  0.05464495
   0.00737936]
 [-0.09518543  0.01428728  0.05765084 ...  0.02357128  0.09081826
  -0.01985878]
 [ 0.03440031 -0.01401784 -0.02677123 ... -0.0211325  -0.01241661
   0.003111  ]
 ...
 [-0.08400045 -0.07249618  0.0619384  ...  0.07563079 -0.04204747
  -0.03541815]
 [-0.05583677  0.08154557  0.00972074 ... -0.03041654  0.03608525
  -0.03019924]

In [142]:
print("w0 = ", clf.coefs_[0][0][0])
print("w1 = ", clf.coefs_[0][1][0])

w0 =  0.008916309642808514
w1 =  -0.10483848163647855


In [143]:
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])

Bias values for first hidden layer:
[-0.03399329 -0.04345295  0.0495508  -0.03303881  0.01167948 -0.07265374
  0.09321166 -0.00621191  0.05318023 -0.07150791  0.0417952  -0.07851507
 -0.03891577 -0.09207154 -0.0294914   0.01522745  0.06727692  0.10420303
 -0.01074004 -0.03123066 -0.02437158  0.12570307 -0.07969989 -0.00024183
  0.09852929 -0.00924887 -0.01735946  0.0907385   0.1249441   0.10383821
 -0.03976441  0.04356402 -0.02292436 -0.06449052  0.04608633 -0.03059235
 -0.0808138  -0.01757793 -0.03642389  0.0879108   0.10162893  0.08939132
 -0.00879857  0.01745482  0.01973908 -0.1102357   0.15859437  0.04341633
 -0.05440787  0.13828982  0.00498179 -0.10557717 -0.0660307  -0.10030421
 -0.03852163 -0.09721671  0.03836401 -0.07169881 -0.02681129 -0.04430081
  0.02382329  0.01689531  0.06799671 -0.02217797 -0.05709427  0.13690059
  0.00649455 -0.13165053 -0.07486093  0.00796466 -0.02054467 -0.04809954
 -0.07570221  0.11613378  0.09469218 -0.08655646  0.06495593  0.06128098
  0.02482314 -0

In [147]:
# Second Approach
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(400, 250), max_iter=2000, alpha=1e-4,
                    solver='sgd', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

mlp.fit(X_train, y_train)
print("Training set score: %f" % mlp.score(X_train, y_train))
print("Test set score: %f" % mlp.score(X_test, y_test))

Iteration 1, loss = 1.54787046
Iteration 2, loss = 1.55720643
Iteration 3, loss = 1.52064286
Iteration 4, loss = 1.50117792
Iteration 5, loss = 1.51143599
Iteration 6, loss = 1.49311631
Iteration 7, loss = 1.48535028
Iteration 8, loss = 1.48509041
Iteration 9, loss = 1.52108092
Iteration 10, loss = 1.53010512
Iteration 11, loss = 1.48844535
Iteration 12, loss = 1.48823449
Iteration 13, loss = 1.49133583
Iteration 14, loss = 1.46651022
Iteration 15, loss = 1.46766692
Iteration 16, loss = 1.47896427
Iteration 17, loss = 1.46576018
Iteration 18, loss = 1.46424887
Iteration 19, loss = 1.46944230
Iteration 20, loss = 1.46096885
Iteration 21, loss = 1.46626906
Iteration 22, loss = 1.44752699
Iteration 23, loss = 1.50089979
Iteration 24, loss = 1.49175066
Iteration 25, loss = 1.46555584
Iteration 26, loss = 1.45196650
Iteration 27, loss = 1.46501381
Iteration 28, loss = 1.46702039
Iteration 29, loss = 1.43843908
Iteration 30, loss = 1.44633294
Iteration 31, loss = 1.47439013
Iteration 32, los

In [118]:
predictions = mlp.predict(X_test)
predictions

array([1, 3, 0, ..., 1, 1, 1])

In [119]:
prob_results = clf.predict_proba(X_test)

In [120]:
y_pred = mlp.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.32      0.19      0.24      1236
           1       0.25      0.49      0.33      1236
           2       0.23      0.08      0.12      1256
           3       0.31      0.44      0.36      1203
           4       0.60      0.41      0.49      1242

    accuracy                           0.32      6173
   macro avg       0.34      0.32      0.31      6173
weighted avg       0.34      0.32      0.31      6173



In [90]:
def Manually_check(X,y):
    PRED = mlp.predict(X)
    LABEL = y
    return PRED,y

In [91]:
Manually_check(X[0:20],y[0:20])

(array([3, 4, 1, 1, 2, 2, 0, 1, 0, 3, 0, 0, 0, 0, 4, 3, 1, 3, 2, 2]),
 array([2, 4, 1, 2, 2, 2, 0, 1, 0, 3, 0, 0, 2, 0, 2, 3, 1, 3, 2, 3]))