In [151]:
import numpy as np
import pandas as pd 
from numpy import array
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [152]:
data = pd.read_csv('/Users/Fox/Desktop/Data Science/Capstone/Codes/EDA-Siqi/EDA.csv', index_col=0)
data

Type  Breed1  Breed2  Gender  Color1  Color2  Color3  MaturitySize  \
0         0     167       0       1       0       6       0             3   
1         0     136       0       1       0       1       0             2   
2         1     175       0       1       1       6       0             2   
3         1     175       0       0       0       1       0             2   
4         1     175       0       1       0       0       0             2   
...     ...     ...     ...     ...     ...     ...     ...           ...   
14987     1      89       0       0       0       6       0             3   
14988     0     137       0       2       0       0       0             2   
14989     0     136     100       2       0       3       5             2   
14990     0     136     102       2       4       5       5             1   
14991     0     137       0       0       3       6       0             3   

       FurLength  Vaccinated  Dewormed  Sterilized  Health  Quantity  \
0              2           0         0           0       0         0   
1              1           1         1           1       0         0   
2              1           2         2           0       0         0   
3              2           2         2           0       0         0   
4              2           0         0           0       0         0   
...          ...         ...       ...         ...     ...       ...   
14987          0           2         2           0       0         0   
14988          1           0         0           0       0         3   
14989          1           2         2           2       0         1   
14990          1           0         2           1       0         4   
14991          2           2         2           2       0         0   

       VideoAmt  PhotoAmt  AdoptionSpeed  AgeBins  Pure_breed  Free_or_NeedFee  
0             0         1              2        0           1                1  
1             0         2              4        0           1                0  
2             0         7              1        0           1                0  
3             0         8              2        0           1                1  
4             0         3              2        0           1                0  
...         ...       ...            ...      ...         ...              ...  
14987         0         1              4        1           1                0  
14988         0         3              2        0           1                0  
14989         0         3              3        4           0                0  
14990         0         5              1        0           0                1  
14991         0         3              3        1           1                0  

[14617 rows x 20 columns]

In [153]:
df = pd.DataFrame(data) 

In [154]:
# Drop Breed1 Breed2
X = df[['Type', 'Gender', 'Color1', 'Color2', 'Color3', 'MaturitySize',
       'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health',
       'Quantity', 'VideoAmt', 'PhotoAmt', 'AgeBins',
       'Pure_breed', 'Free_or_NeedFee']].values

In [155]:
y = np.array(df['AdoptionSpeed'].tolist())

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [157]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(50, 20), random_state=1)
clf.fit(X, y)
print("Training set score: %f" % clf.score(X_train, y_train))
print("Test set score: %f" % clf.score(X_test, y_test))

Training set score: 0.415633
Test set score: 0.401847


/Users/Fox/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [158]:
y_pred = clf.predict(X_test)

In [159]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.36      0.31      0.33       578
           1       0.42      0.17      0.24       652
           2       0.36      0.43      0.39       804
           3       0.45      0.66      0.54       817
           4       0.00      0.00      0.00        73

    accuracy                           0.40      2924
   macro avg       0.32      0.31      0.30      2924
weighted avg       0.39      0.40      0.38      2924



/Users/Fox/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [160]:
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])

weights between input and first hidden layer:
[[-1.08015821e-02  7.60939629e-02 -2.74812158e-01 -4.03899267e-02
  -2.25551893e-01 -1.23897956e-01 -4.83062628e-01  7.44893939e-02
  -1.83015019e-01 -5.92348608e-02  6.48037511e-02  2.37420628e-01
  -1.65182474e-01 -2.25345285e-02 -2.96299395e-01 -3.41764796e-02
   1.49980801e-01 -1.94909724e-01 -4.04743416e-01 -4.95298480e-02
   2.02188191e-01  4.08423742e-01 -2.96697299e-01  4.44648798e-01
   5.47234745e-01 -1.82825067e-02 -2.27539398e-01 -2.73363042e-01
  -3.91495611e-01  4.75397133e-01 -3.30978675e-01 -9.23722502e-02
   4.98911278e-01  3.15934545e-01  2.90047292e-01 -5.76029196e-01
   1.55213853e-01  5.53642620e-01 -1.98663324e-01 -3.48564802e-02
   3.40983638e-01  1.19544575e-01 -9.87430589e-02  1.33974634e-01
  -3.67659357e-01  3.19687664e-01  3.59921727e-01  1.83865236e-01
  -2.04667815e-01 -3.81473596e-01]
 [-4.27717340e-01 -8.13093986e-02 -2.43052032e-01 -3.87330905e-01
   7.85643899e-02 -6.46360814e-01 -1.31379505e-01 -3.90003842

In [161]:
print("w0 = ", clf.coefs_[0][0][0])
print("w1 = ", clf.coefs_[0][1][0])

w0 =  -0.010801582145105163
w1 =  -0.4277173402730053


In [162]:
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])

Bias values for first hidden layer:
[ 0.29125221 -0.05417281 -0.04460572  0.03278668 -0.21341964  0.42584795
  0.30204928  0.52420931 -0.1017441  -0.32788903  0.05885043  0.12268569
  0.27527179 -0.20856862  0.23249662  0.04270127  0.24795966  0.22803866
 -0.44233788  0.72005214 -0.21263452 -0.09889703 -0.08896461 -0.80595093
  0.09790973 -0.05138419 -0.1338594  -0.29079161  0.18658516  0.11313906
 -0.30051842 -0.25197066  0.10721609 -0.00678107  0.48308657 -0.29779301
 -0.07508983  0.07221026  0.31909223  0.86860387 -0.07558453  0.07670519
 -0.0008877   0.09432474  0.34035616  0.1007482   0.41467942 -0.14956309
  0.08471959 -0.16131774]

Bias values for second hidden layer:
[-0.18235028  0.09143197  0.298699   -0.00196421  0.16784986  0.00937275
 -0.46424261 -0.00095167 -0.18392112 -0.02758631 -0.54650475  0.26651379
  0.02257654  0.30763668  0.00906427 -0.30144054  0.83521791  0.05459248
 -0.20762087  0.32028516]


## Second Approach

In [171]:
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30), max_iter=2000, alpha=1e-4,
                    solver='sgd', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

mlp.fit(X_train, y_train)
print("Training set score: %f" % mlp.score(X_train, y_train))
print("Test set score: %f" % mlp.score(X_test, y_test))

Iteration 1, loss = 1.45767886
Iteration 2, loss = 1.41609300
Iteration 3, loss = 1.40821170
Iteration 4, loss = 1.40349209
Iteration 5, loss = 1.40237822
Iteration 6, loss = 1.40181943
Iteration 7, loss = 1.39808828
Iteration 8, loss = 1.39665743
Iteration 9, loss = 1.39658059
Iteration 10, loss = 1.39360897
Iteration 11, loss = 1.39240045
Iteration 12, loss = 1.39216231
Iteration 13, loss = 1.39235721
Iteration 14, loss = 1.38697160
Iteration 15, loss = 1.38864993
Iteration 16, loss = 1.38963269
Iteration 17, loss = 1.38738679
Iteration 18, loss = 1.38444711
Iteration 19, loss = 1.38357993
Iteration 20, loss = 1.38174196
Iteration 21, loss = 1.38213418
Iteration 22, loss = 1.38354334
Iteration 23, loss = 1.38183143
Iteration 24, loss = 1.37913767
Iteration 25, loss = 1.37715149
Iteration 26, loss = 1.37807733
Iteration 27, loss = 1.37643654
Iteration 28, loss = 1.37565858
Iteration 29, loss = 1.37653251
Iteration 30, loss = 1.37399342
Iteration 31, loss = 1.37474464
Iteration 32, los

Iteration 253, loss = 1.29743085
Iteration 254, loss = 1.30525993
Iteration 255, loss = 1.29633885
Iteration 256, loss = 1.29792738
Iteration 257, loss = 1.29797623
Iteration 258, loss = 1.29641935
Iteration 259, loss = 1.29952870
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Training set score: 0.433764
Test set score: 0.338577


In [172]:
predictions = mlp.predict(X_test)
predictions

array([3, 3, 3, ..., 3, 0, 3])

In [173]:
prob_results = clf.predict_proba(X_test)

In [174]:
prob_results

array([[0.24169106, 0.1391937 , 0.2083949 , 0.35850327, 0.05221708],
       [0.09507714, 0.16874136, 0.16172881, 0.5611028 , 0.01334989],
       [0.07691399, 0.2398949 , 0.20817601, 0.46926019, 0.00575492],
       ...,
       [0.11633844, 0.09341637, 0.12795963, 0.64285985, 0.01942571],
       [0.27560859, 0.27703072, 0.34417345, 0.07483219, 0.02835504],
       [0.17155104, 0.23072544, 0.26002705, 0.30412775, 0.03356872]])

In [175]:
y_pred = mlp.predict(X_test)

In [176]:
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.24      0.22      0.23       578
           1       0.27      0.07      0.11       652
           2       0.31      0.44      0.36       804
           3       0.43      0.57      0.49       817
           4       0.00      0.00      0.00        73

    accuracy                           0.34      2924
   macro avg       0.25      0.26      0.24      2924
weighted avg       0.31      0.34      0.31      2924



In [177]:
def Manually_check(X,y):
    PRED = mlp.predict(X)
    LABEL = y
    return PRED,y

In [178]:
Manually_check(X[0:20],y[0:20])

(array([2, 3, 2, 1, 2, 0, 3, 2, 0, 3, 2, 0, 2, 0, 3, 1, 2, 3, 2, 0]),
 array([2, 4, 1, 2, 2, 2, 0, 1, 0, 3, 0, 0, 2, 0, 2, 3, 1, 3, 2, 3]))

In [149]:
mlp.predict([X[1]])

array([4])

In [150]:
mlp.predict([[1, 1, 1, 9, 0, 2, 2, 0, 4, 0, 1, 2, 1, 4, 2, 1, 2, 0]])

array([2])